# Generated by Django 3.1.12 on 2021-06-04 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(help_text='Enter Product Barcode ', max_length=13)),
                ('name', models.CharField(help_text='Enter Product Title', max_length=200)),
                ('category', models.CharField(help_text='Enter Product Category', max_length=200)),
                ('description', models.TextField(help_text='Enter Product Description')),
                ('unitCost', models.FloatField(help_text='Enter Product Unit Cost')),
                ('quantityInStock', models.FloatField(help_text='Enter Product Quantity')),
            ],
        ),
    ]
