# Generated by Django 3.1.12 on 2021-06-04 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='quantityInStock',
            new_name='quantity_in_stock',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='unitCost',
            new_name='unit_cost',
        ),
    ]
